[package]
name = "rust-lalrpop-experiment"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
