[workspace]
members = [
    "crates/ast",
    "crates/cli",
    "crates/parser",
    "crates/generators/idl",
    "crates/generators/codegen-core",
    "crates/generators/python",
    "crates/generators/rust",
    "crates/wasm",
]
resolver = "2"
